# config file for defis

datagouvfr:
  # data.gouv.fr base URL
  base_url: https://www.data.gouv.fr
  # oauth settings
  oauth_client_id:
  # pkce client secret, explicitely public
  oauth_client_secret:

universe:
  # "universe" topic id
  topic_id: 65c0f2e2fb22540a9e91a2e4
  # universe name, used as bouquets tag
  name: defis

robots:
  disallow:
    - /
  sitemap:

# UI customizations
website:
  title: 'defis.data.gouv.fr'
  rf_title: 'RÉPUBLIQUE<br>
    FRANÇAISE'
  service_logo: '/logos/defis-logo.svg'
  badge:
    display: true
    text: 'BETA'
    style: 'blue-cumulus'
  # leave empty if not pertinent
  homepage:
    title: 'Apprendre avec l’open data'
    subtitle: 'Se former et utiliser des données ouvertes pour répondre à des enjeux sociaux et environnementaux.'
    sections:
      - title:
        content: >-

          Les données ouvertes (open data) sont des données brutes téléchargeables en accès libre et gratuit qui peuvent être utilisées par toutes et tous. Elles permettent de créer des analyses, des services ou des produits sur une diversité de sujets (santé, emploi, urbanisme, éducation, mobilités, etc.).
        sub_section_datasets:
        sub_section_cards:
        sub_section_tiles:
        sub_section_buttons:
      - title: Des défis open data
        content: >-

          La communauté open data et l’équipe de data.gouv.fr vous proposent de mettre à contribution et de développer vos compétences en réalisant des projets utiles à partir de données ouvertes.


          Les défis proposés s’adressent notamment à toutes celles et ceux qui souhaitent s’exercer ou apprendre à exploiter des données en travaillant sur des projets concrets.
        sub_section_datasets:
        sub_section_cards:
        sub_section_tiles:
        sub_section_buttons:
      - title:
        content:
        sub_section_datasets:
        sub_section_cards:
          title:
          cards:
            - id: '65b76f15d7874915c8e41298'
              name: 'Impact Diagnostics de Performance Energétique'
              description: 'Quel impact de la classe DPE sur les consommations énergétiques ? Défi porté par Enedis'
              url: '/defis/diagnostics-de-performance-energetique'
              image_url: 'https://raw.githubusercontent.com/thanhhale7/images/main/odu_enedis4.png'
            - id: '65b10aa72d0c187ecf296930'
              name: 'Offre culturelle'
              description: "Comment valoriser l'offre culturelle et favoriser l'accès à la culture ?"
              url: '/defis/offre-culturelle'
              image_url: 'https://raw.githubusercontent.com/thanhhale7/images/main/odu_culture3.png'
            - id: '65b22219ffcf892bd066df76'
              name: 'Elections'
              description: 'Quels liens entre vote et caractéristiques socio-démographiques ?'
              url: '/defis/elections'
              image_url: 'https://raw.githubusercontent.com/thanhhale7/images/main/odu_elections3.png'
            - id: '65b10beae24f409e31c547a5'
              name: 'Changement climatique'
              description: 'Quelle évolution du climat en France depuis le début du XXe siècle ?'
              url: '/defis/changement-climatique'
              image_url: 'https://raw.githubusercontent.com/thanhhale7/images/main/odu_climat3.png'
            - id: '65b76b8536f029909a82ca1c'
              name: 'Commerces de centre-ville'
              description: 'Quelle est la structure du tissu commercial ?'
              url: '/defis/commerces-de-centre-ville'
              image_url: 'https://raw.githubusercontent.com/thanhhale7/images/main/odu_commerces3.png'
            - id: '65a92352ddd3d98e460e83f3'
              name: 'Infrastructures cyclables'
              description: 'Quels liens entre accidentologie à vélo et infrastructures cyclables ?'
              url: '/defis/infrastructures-cyclables'
              image_url: 'https://raw.githubusercontent.com/thanhhale7/images/main/odu_velo3.png'
            - id: '65a92372953d21f206abb110'
              name: 'Energie en France'
              description: 'Quelles tensions énergétiques passées et futures en France ?'
              url: '/defis/energie-en-france'
              image_url: 'https://raw.githubusercontent.com/thanhhale7/images/main/energie3_odu.png'
            - id: '65a9237ed493a309fc872e4a'
              name: 'Carte scolaire'
              description: 'Comment permettre de savoir dans quel établissement inscrire un enfant ?'
              url: '/defis/carte-scolaire'
              image_url: 'https://raw.githubusercontent.com/thanhhale7/images/main/odu_ecole4.png'
            - id: '65a923a083cf5f728c9934b3'
              name: 'Véhicules électriques'
              description: 'La répartition des infrastructures de recharge est-elle adaptée ?'
              url: '/defis/vehicules-electriques'
              image_url: 'https://raw.githubusercontent.com/thanhhale7/images/main/odu_voiture3.png'
            - id: '65a9238c202514467c0163d2'
              name: 'Plan France Relance'
              description: "Quels impacts des aides distribués sur l'économie et la transition écologique ?"
              url: '/defis/plan-france-relance'
              image_url: 'https://raw.githubusercontent.com/thanhhale7/images/main/odu_francerelance3.png'
            - id: '66a0fdf41a40f23f40025444'
              name: 'Accès au sport'
              description: "Sport pour tous : Évaluer et améliorer l'égalité d'accès aux activités sportives en France"
              url: 'defis/acces-au-sport'
              image_url: 'https://raw.githubusercontent.com/thanhhale7/images/main/defi-acces-au-sport.jpg'
            - id: '66a0ffa8d8f03afc1d474a53'
              name: 'JOP2024 et offre culturelle'
              description: "Jeux Olympiques et Paralympiques : Enrichissez l'expérience et mettez en valeur l'offre culturelle"
              url: 'defis/jop2024-et-offre-culturelle'
              image_url: 'https://raw.githubusercontent.com/thanhhale7/images/main/defi-jo-offre-culturelle.jpg'
            - id: '66a10128a66990ed3d718a53'
              name: 'JOP2024 et qualité de l’air'
              description: "Jeux Olympiques et Paralympiques : enjeux de pollution de l'air dans le cadre d'une activité physique"
              url: 'defis/jop2024-et-qualite-de-lair'
              image_url: 'https://raw.githubusercontent.com/thanhhale7/images/main/defi-jo-qualite-de-l%27air.jpg'

        sub_section_tiles:
        sub_section_buttons:
    meta_description:
  header_button:
    display: false
    label: 'Donnez votre avis'
    link: https://tally.so/r/wQ7y47
  header_search:
    display: false
  search_bar:
    display: false
    placeholder: 'Rechercher un jeu de données'
  secondary_search:
    display: false
    name:
    link:
  menu:
    - text: Open Data University
      to: /opendatauniversity
    - text: Guides
      to: https://guides.data.gouv.fr/
  router:
    disable:
      - organizations_routes
    pages:
      - title: 'Open Data University'
        id: 'opendatauniversity'
        route: '/opendatauniversity'
        url: '/defis/pages/opendatauniversity.md'
      - title: 'Accessibilité'
        id: 'accessibility'
        route: '/accessibility'
        url: '/defis/pages/accessibility.md'
  show_quality_component: true
  show_dataset_metadata_panel: false
  list_search_topics:
  url_search_topics: 'defis'
  oauth_option: false
  footer_phrase: 'Ce site présente des exemples de défis de réutilisations de données publiques sélectionnés par l’équipe data.gouv.fr en collaboration avec les producteurs de données.'
  footer_external_links:
    - label: 'data.gouv.fr'
      href: 'https://www.data.gouv.fr'
    - label: 'Association Latitudes'
      href: 'https://www.latitudes.cc/'
  footer_mandatory_links:
    - label: 'Licences'
      href: 'https://www.data.gouv.fr/fr/pages/legal/licences/'
    - label: "Conditions générales d'utilisation"
      href: 'https://www.data.gouv.fr/fr/terms/'
    - label: 'Politique de confidentialité'
      href: 'https://www.data.gouv.fr/fr/suivi/'
    - label: 'Accessibilité : non conforme'
      to: '/accessibility'
  logo_operator: ''
  notice:
    display: false
    content: Notice avec un [lien beta](/beta) et du _style_
    closeable: false
  # display settings
  pagination_sizes:
    organizations_list: 9
    topics_list: 100
    files_list: 6
  home_banner_colors:
    - '#D6DAF7'
    - '#DBA8A8'
    - '#1258EB'
  env: 'prod'
  matomo:
    host:
    siteId:
  discussions:
    dataset:
      display: true
      create: false
    topic:
      display: false
      create: false
  datasets:
    organization_filter: false
    add_to_bouquet: false
    # similar to QUALITY_METADATA_BACKEND_IGNORE on data.gouv.fr
    harvest_backends_quality_warning: []
    show_extended_information_panel: false
  topics:
    useThemes: false
    pageAllTopics: false
    displayMetadata: false
    activateReadMore: false
    datasetEditorialization: false

# list of organisations' ids that should be handled by the portal
# to find an id go to https://www.data.gouv.fr/fr/organizations/ministere-de-la-transition-ecologique/
# then Informations > ID at the bottom of the page
organizations:
