# config file for defis

datagouvfr:
  # data.gouv.fr base URL
  base_url: https://www.data.gouv.fr
  # oauth settings
  oauth_client_id:
  # pkce client secret, explicitely public
  oauth_client_secret:

universe:
  # "universe" topic id
  topic_id: 6571f222129681e83de11aa2 # meteo-test
  # universe name, used as bouquets tag
  name: defis

# UI customizations
website:
  title: 'defis.data.gouv.fr'
  rf_title: 'RÉPUBLIQUE<br>
    FRANÇAISE'
  service_logo: '/logos/defis-logo.svg'
  badge:
    display: true
    text: 'BETA'
    style: 'blue-cumulus'
  # leave empty if not pertinent
  homepage_title: 'Apprendre avec l’open data'
  homepage_subtitle: 'Se former et utiliser des données ouvertes pour répondre à des enjeux sociaux et environnementaux.'
  homepage_text_below_hero:
    display: true
    html: >-
      <p>Les données ouvertes (open data) sont des données brutes téléchargeables en accès libre et
          gratuit qui peuvent être utilisées par toutes et tous. Elles permettent de créer des analyses,
          des services ou des produits sur une diversité de sujets (santé, emploi, urbanisme, éducation,
          mobilités, etc.).</p>
      <h4>Des défis open data</h4>
      <p>La communauté open data et l’équipe de data.gouv.fr vous proposent de mettre à contribution et de
          développer vos compétences en réalisant des projets utiles à partir de données ouvertes.</p>
      <p>Les défis proposés s’adressent notamment à toutes celles et ceux qui souhaitent s’exercer ou
          apprendre à exploiter des données en travaillant sur des projets concrets, dans le cadre d’une
          formation ou accompagnés des guides de data.gouv.fr.</p>
  homepage_text_below_topics:
    display: true
    html: >-
      <h4>L&#39Open Data University</h4>
      <p>Ces défis ont été développés dans le cadre de <a
              href="https://www.opendatauniversity.org/">l’Open Data University</a>, un programme
          d’enseignement à la réutilisation des données publiques porté par <a
              href="https://www.latitudes.cc/">l&#39association Latitudes</a> et dont data.gouv.fr est
          partenaire.</p>
      <p><a href=/defis/pages/opendatauniversity>En savoir plus sur l’Open Data University.</a></p>
  header_button:
    display: false
    label: 'Donnez votre avis'
    link: https://tally.so/r/wQ7y47
  search_bar:
    display: false
    placeholder: 'Rechercher un jeu de données'
  secondary_search:
    display: false
    name:
    link:
  router_items:
    - name: 'Accueil'
      id: 'home'
      linkPage: '/'
      type: 'component'
      display_menu: false
    - name: 'Défis'
      id: 'topics'
      linkPage: '/topics'
      type: 'component'
      display_menu: true
    - name: 'Open Data University'
      id: 'opendatauniversity'
      linkPage: '/opendatauniversity'
      type: 'page'
      display_menu: true
      url: '/defis/pages/opendatauniversity.md'
    - name: 'Accessibilité'
      id: 'accessibility'
      linkPage: '/accessibility'
      type: 'page'
      display_menu: false
      url: '/defis/pages/accessibility.md'
    - name: 'Guides'
      id: 'guides'
      linkPage: 'https://guides.data.gouv.fr/'
      type: 'external'
      display_menu: true
      url: 'https://guides.data.gouv.fr/'
  # img should be square
  home_buttons:
  show_topic_charts: true
  show_quality_component: true
  show_dataset_metadata_panel: false
  list_highlighted_topics:
    - id: '65a92352ddd3d98e460e83f3'
      name: 'Infrastructures cyclables'
    - id: '65a92372953d21f206abb110'
      name: 'Energie en France'
    - id: '65a9237ed493a309fc872e4a'
      name: 'Carte scolaire'
    - id: '65a9238c202514467c0163d2'
      name: 'Plan France Relance'
    - id: '65a923a083cf5f728c9934b3'
      name: 'Véhicules électriques'
    - id: '65b10aa72d0c187ecf296930'
      name: 'Offre culturelle'
    - id: '65b10beae24f409e31c547a5'
      name: 'Changement climatique en France'
    - id: '65b22219ffcf892bd066df76'
      name: 'Elections'
  url_highlighted_topics: 'topics'
  type_highlighted_topics: 'card'
  oauth_option: false
  footer_phrase: 'Ce site présente des exemples de défis de réutilisations de données publiques sélectionnés par l’équipe data.gouv.fr en collaboration avec les producteurs de données.'
  footer_external_links:
    - label: 'data.gouv.fr'
      href: 'https://www.data.gouv.fr'
    - label: 'Association Latitudes'
      href: 'https://www.latitudes.cc/'
  footer_mandatory_links:
    - label: 'Licences'
      href: 'https://www.data.gouv.fr/fr/pages/legal/licences/'
    - label: "Conditions générales d'utilisation"
      href: 'https://www.data.gouv.fr/fr/terms/'
    - label: 'Politique de confidentialité'
      href: 'https://www.data.gouv.fr/fr/suivi/'
    - label: 'Accessibilité : non conforme'
      to: '/accessibility'
  logo_operator: ''
  # display settings
  pagination_sizes:
    organizations_list: 9
    topics_list: 100
    files_list: 6
  home_banner_colors:
    - '#D6DAF7'
    - '#DBA8A8'
    - '#1258EB'
  env: 'prod'
  matomo:
    host: 'https://stats.data.gouv.fr'
    siteId: 292
  discussions:
    dataset:
      display: true
      create: false
    topic:
      display: false
      create: false

# list of organisations' ids that should be handled by the portal
# to find an id go to https://www.data.gouv.fr/fr/organizations/ministere-de-la-transition-ecologique/
# then Informations > ID at the bottom of the page
organizations:
