# config file for ecospheres-front

datagouvfr:
  # data.gouv.fr base URL (use www subdomain on prod)
  base_url: https://www.data.gouv.fr
  # oauth settings
  oauth_client_id: 65e9c33ee89b6256ad069a31
  # pkce client secret, explicitely public
  oauth_client_secret: tTD6KpvTo8uGnD1K8XMjrZN3pv0iwZZaIAYxkCga4jBFupeRdp

universe:
  # "universe" topic id
  topic_id: 65e9aa6cb5c809c30c70ee02
  # universe name, used as bouquets tag
  name: univers-ecospheres

robots:
  disallow:
    - /admin
    - /datasets
    - /organizations
  sitemap: https://ecologie.data.gouv.fr/sitemap.xml

# UI customizations
website:
  title: 'ecologie.data.gouv.fr'
  rf_title: 'RÉPUBLIQUE<br>FRANÇAISE'
  service_logo: '/logos/ecospheres-logo.svg'
  badge:
    display: true
    text: 'BETA'
    style: 'blue-cumulus'
  # leave empty if not pertinent
  logo_operator:
  homepage:
    title: 'La plateforme des données de la transition écologique'
    subtitle:
    below_hero:
    below_topics:
    meta_description: ecologie.data.gouv.fr référence et centralise les données de la transition écologique.
  header_button:
    display: true
    label: 'Donnez votre avis'
    link: https://tally.so/r/wLWrzp
  header_search:
    display: true
    placeholder: Rechercher...
    dropdown:
      - text: Rechercher {} dans les <strong>bouquets</strong>
        route: bouquets
      - text: Rechercher {} dans les <strong>jeux de données</strong>
        route: datasets
  search_bar:
    display: true
    placeholder: Rechercher une donnée environnementale
  secondary_search:
    display: false
    name:
    link:
  footer_phrase: "Ce site est une déclinaison thématique de data.gouv.fr sur les données relatives à l'écologie."
  footer_external_links:
    - label: 'ecologie.gouv.fr'
      href: 'https://ecologie.gouv.fr'
    - label: 'data.gouv.fr'
      href: 'https://www.data.gouv.fr'
    - label: 'gouvernement.fr'
      href: 'https://www.gouvernement.fr'
  footer_mandatory_links:
    - label: "Conditions générales d'utilisation"
      to: '/terms'
    - label: 'Politique de confidentialité'
      href: 'https://www.data.gouv.fr/fr/suivi/'
    - label: 'Accessibilité : non conforme'
      to: '/accessibility'
  notice:
    display: true
    content: Vous naviguez sur une version beta d'ecologie.data.gouv. En savoir plus sur [nos travaux en cours](https://ecospheres.gitbook.io/travaux-en-cours/).
    closeable: false
  menu:
    - text: Accueil
      to: /
    - text: Données
      to: /datasets
    - text: Bouquets
      to: /bouquets
    - text: A propos
      to: /about
  router:
    disable:
      - topics
    pages:
      - title: 'À propos'
        id: 'about'
        route: '/about'
        url: '/ecospheres/pages/about.md'
      - title: 'Accessibilité'
        id: 'accessibility'
        route: '/accessibility'
        url: '/ecospheres/pages/accessibility.md'
      - title: "Conditions générales d'utilisation"
        id: 'terms'
        route: '/terms'
        url: '/ecospheres/pages/terms.md'
  home_buttons:
  show_topic_charts: false
  show_quality_component: true
  list_highlighted_topics:
  url_highlighted_topics:
  type_highlighted_topics:
  oauth_option: true
  pagination_sizes:
    organizations_list: 9
    topics_list: 100
    files_list: 6
  contact_email: ecospheres@developpement-durable.gouv.fr
  home_banner_colors:
    - '#D6E3A1'
    - '#BFDCB7'
    - '#A7D4CD'
  matomo:
    host: 'https://stats.data.gouv.fr'
    siteId: 299
  discussions:
    dataset:
      display: true
      create: true
    topic:
      display: true
      create: true
  datasets:
    organization_filter: true
    add_to_bouquet: true
    # similar to QUALITY_METADATA_BACKEND_IGNORE on data.gouv.fr
    harvest_backends_quality_warning:
      - CSW-ISO-19139
    show_extended_information_panel: true

themes:
  - name: Se loger
    color: 043574
    textColor: FFFFFF
    subthemes:
      - name: Construction et rénovation des logements
      - name: Aménagements des villes
  - name: Produire
    color: 1E929E
    textColor: FFFFFF
    subthemes:
      - name: Nucléaire
      - name: Tertiaire (incluant les bâtiments publics de l'État et des collectivités, hors logement)
      - name: Production d'électricité décarbonée (hors nucléaire)
  - name: Se nourrir
    color: 8AC6CD
    subthemes:
      - name: Alimentation
      - name: Agriculture et pêche
  - name: Consommer
    color: A5BD0B
    subthemes:
      - name: Consommation plus durable (ménages)
      - name: Numérique responsable
      - name: Achats durables (de l'État, des collectivités et des entreprises)
  - name: Préserver
    color: BFD899
    subthemes:
      - name: Eau
      - name: Sols
      - name: Océans et mers
      - name: Forêt
  - name: Se déplacer
    color: D6E099
    subthemes:
      - name: Voitures et infrastructures routières
      - name: Mobilité courte distance (hors voiture)
      - name: Mobilité longue distance (avion, train)
  - name: Chantiers transverses
    color: EAEEFE
    subthemes:
      - name: Le financement qui permet de définir des trajectoires d'investissement crédibles et cohérentes
      - name: La planification et la différenciation territoriale selon les caractéristiques et les spécificités de chaque territoire, incluant les territoires ultra-marins
      - name: La transition des filières avec la gestion des emplois, des formations et des compétences
      - name: Les données environnementales
      - name: Les services publics exemplaires
      - name: La transition juste et les mesures d’accompagnement, pour ne laisser personne au bord du chemin
      - name: La sobriété des usages et des ressources

organizations:
  - ademe
  - agence-de-l-eau-rhone-mediterranee-et-corse
  - agence-de-leau-seine-normandie-1
  - agence-nationale-de-la-cohesion-des-territoires
  - agence-nationale-de-lhabitat
  - agence-nationale-pour-la-renovation-urbaine
  - agence-ore-3
  - airparif-1
  - atmo-auvergne-rhone-alpes
  - atmo-bourgogne-franche-comte
  - atmo-grand-est
  - atmosud
  - bureau-de-recherches-geologiques-et-minieres
  - centre-scientifique-et-technique-du-batiment
  - cerema
  - commission-de-regulation-de-lenergie
  - datagrandest
  - ddt-de-meurthe-et-moselle
  - ddt-des-vosges
  - ddt-jura
  - direction-departementale-des-territoires-de-saone-et-loire-71
  - direction-departementale-des-territoires-du-bas-rhin-67
  - direction-departementale-des-territoires-du-doubs
  - direction-departementale-des-territoires-du-rhone-1
  - direction-departementale-des-territoires-et-de-la-mer-de-lherault
  - direction-departementale-des-territoires-et-de-la-mer-de-loire-atlantique
  - direction-departementale-des-territoires-et-de-la-mer-dille-et-vilaine
  - direction-regionale-de-lenvironnement-de-lamenagement-et-du-logement-de-laquitaine
  - direction-regionale-de-lenvironnement-de-lamenagement-et-du-logement-de-lauvergne
  - direction-regionale-de-lenvironnement-de-lamenagement-et-du-logement-de-normandie
  - direction-regionale-de-lenvironnement-de-lamenagement-et-du-logement-du-languedoc-roussillon
  - direction-regionale-de-lenvironnement-de-lamenagement-et-du-logement-poitou-charentes
  - direction-regionale-de-lenvironnement-et-du-logement-bourgogne-franche-comte
  - direction-regionale-et-interdepartementale-de-lenvironnement-de-lamenagement-et-des-transports-1
  - do-terr-geo-centre
  - dreal-nouvelle-aquitaine
  - dreal-pays-de-la-loire-direction-regionale-de-lenvironnement-de-lamenagement-et-du-logement-pays-de-la-loire
  - dreal-provence-alpes-cote-dazur
  - electricite-reseau-distribution-france
  - engie-mobilites-electriques
  - equipe-transport-data-gouv-fr
  - federation-des-parcs-naturels-regionaux-de-france
  - fluo-grand-est
  - geo2france
  - gip-bretagne-environnement
  - grdf
  - ile-de-france-mobilites
  - institut-francais-de-recherche-pour-lexploitation-de-la-mer
  - institut-national-de-l-information-geographique-et-forestiere
  - irstea
  - jvmalin
  - la-direction-regionale-de-lenvironnement-de-lamenagement-et-du-logement-provence-alpes-cote-dazur
  - ligair
  - meteo-france
  - ministere-de-l-egalite-des-territoires-et-du-logement
  - ministere-de-la-transition-ecologique
  - morbihan-energies
  - observatoire-de-recherche-montpellierain-de-lenvironnement
  - office-national-des-forets
  - office-public-de-lhabitat-des-landes
  - oise-mobilite-syndicat-mixte-des-transports-collectifs-de-loise
  - open-data-reseaux-energies-1
  - parc-national-de-forets
  - parc-national-des-cevennes
  - parc-national-des-ecrins
  - parc-naturel-regional-de-la-montagne-de-reims
  - parc-naturel-regional-de-la-montagne-de-reims-1
  - parc-naturel-regional-des-vosges-du-nord
  - parc-naturel-regional-du-morvan
  - parc-naturel-regional-du-vercors
  - parcs-nationaux-de-france
  - parcs-naturels-regionaux-de-provence-alpes-cote-dazur
  - regie-autonome-des-transports-parisiens-ratp
  - reseau-de-transport-delectricite
  - section-cadastre-topographie-de-la-polynesie-francaise
  - shom
  - sncf
  - societe-du-grand-paris
  - star
  - syndicat-mixte-des-milieux-aquatiques-et-des-rivieres-de-laude
  - syndicat-mixte-des-mobilites-de-laire-grenobloise
  - syndicat-mixte-eptb-meurthe-madon
  - systeme-d-information-sur-l-eau
  - systeme-dinformation-sur-la-biodiversite
  - twisto
