# config file for ecospheres-front

datagouvfr:
  # data.gouv.fr base URL (use www subdomain on prod)
  base_url: https://demo.data.gouv.fr
  # oauth settings
  oauth_client_id: 66e30254d3cc5d5b52a4b6ec

universe:
  # "universe" topic id
  topic_id: 65141cd780d73f98142e9265
  # universe name, used as bouquets tag
  name: ecospheres

robots:
  disallow:
  sitemap:
  meta: 'noindex, nofollow'

# UI customizations
website:
  title: 'ecologie.data.gouv.fr'
  rf_title: 'RÉPUBLIQUE<br>FRANÇAISE'
  service_logo: '/logos/ecospheres-logo.svg'
  badge:
    display: true
    text: 'BETA'
    style: 'blue-cumulus'
  # leave empty if not pertinent
  logo_operator:
    src: '/logos/ecospheres-logo.svg'
    show_in_header: false
    footer:
      width: '40px'
      height: '219px'
  homepage:
    title:
    subtitle:
    sections:
      - title:
        content:
        sub_section_datasets:
        sub_section_cards:
        sub_section_tiles:
        sub_section_buttons:
    meta_description: ecologie.data.gouv.fr référence et centralise les données de la transition écologique.
  header_button:
    display: true
    label: 'Donnez votre avis'
    link: https://tally.so/r/wLWrzp
  header_search:
    display: true
    placeholder: Rechercher...
    dropdown:
      - text: Rechercher {} dans les <strong>jeux de données</strong>
        route: datasets
      - text: Rechercher {} dans les <strong>bouquets</strong>
        route: bouquets
  search_bar:
    display: true
    placeholder: Rechercher une donnée environnementale
  secondary_search:
    display: false
    name:
    link:
  footer_phrase: 'Ce site est une déclinaison thématique de data.gouv.fr sur les données relatives à la transition écologique et énergétique, réalisé par le Ministère de la Transition écologique, de l’Énergie, du Climat et de la Prévention des risques.'
  footer_external_links:
    - label: 'data.gouv.fr'
      href: 'https://www.data.gouv.fr'
      title: 'data.gouv.fr - nouvelle fenêtre'
    - label: 'legifrance.gouv.fr'
      href: 'https://www.legifrance.gouv.fr/'
      title: 'legifrance - nouvelle fenêtre'
    - label: 'ecologie.gouv.fr'
      href: 'https://ecologie.gouv.fr'
      title: 'ecologie.gouv.fr - nouvelle fenêtre'
    - label: 'gouvernement.fr'
      href: 'https://www.gouvernement.fr'
      title: 'gouvernement.fr - nouvelle fenêtre'
  footer_mandatory_links:
    - label: 'Plan du site'
      to: '/sitemap'
    - label: "Conditions générales d'utilisation"
      to: '/terms'
    - label: 'Politique de confidentialité'
      href: 'https://www.data.gouv.fr/fr/suivi/'
    - label: 'Accessibilité : partiellement conforme'
      to: '/accessibility'
  notice:
    display: true
    content: ⚠️ Vous naviguez sur une version de développement d'ecologie.data.gouv.fr ⚠️
    closeable: false
  menu:
    - text: Accueil
      to: /
    - text: Données
      to: /datasets
    - text: Bouquets
      to: /bouquets
    - text: Indicateurs
      to: /indicators
    - text: Organisations
      to: /organizations
    - text: A propos
      to: /about
  router:
    disable:
      - topics
    pages:
      - title: 'À propos'
        id: 'about'
        route: '/about'
        url: '/ecospheres/pages/about.md'
      - title: 'Accessibilité'
        id: 'accessibility'
        route: '/accessibility'
        url: '/ecospheres/pages/accessibility.md'
      - title: "Conditions générales d'utilisation"
        id: 'terms'
        route: '/terms'
        url: '/ecospheres/pages/terms.md'
  show_quality_component: true
  list_search_topics:
  url_search_topics:
  oauth_option: true
  pagination_sizes:
    organizations_list: 9
    topics_list: 100
    files_list: 6
  contact_email: ecospheres@developpement-durable.gouv.fr
  home_banner_colors:
    - '#D6E3A1'
    - '#BFDCB7'
    - '#A7D4CD'
  matomo:
    host: 'https://stats.data.gouv.fr'
    siteId:
  discussions:
    dataset:
      display: true
      create: true
    topic:
      display: true
      create: true
  datasets:
    organization_filter: true
    add_to_bouquet: true
    # similar to QUALITY_METADATA_BACKEND_IGNORE on data.gouv.fr
    harvest_backends_quality_warning:
      - CSW-ISO-19139
    show_extended_information_panel: true
  sitemap:
    - name: Accueil
      path: /
    - name: Bouquets
      path: /bouquets
    - name: Jeux de données
      path: /datasets
    - name: Organisations
      path: /organizations
    - name: À propos
      path: /about
    - name: Conditions générales d’utilisation
      path: /terms
    - name: Accessibilité
      path: /accessibility
  search_config:
    header_search:
      display: true
      placeholder: Rechercher...
      dropdown:
        - text: Rechercher {} dans les <strong>jeux de données</strong>
          route: datasets
        - text: Rechercher {} dans les <strong>bouquets</strong>
          route: bouquets
    pages:
      - name: bouquets
        slug: bouquets
        type: topics
        config_type:
          organization:
        extras_key: ecospheres
        list_all: true
        display_metadata: true
        activate_read_more: true
        dataset_editorialization: true
        can_add:
          everyone: true
          authorized_users:
        labels:
          search_page_title: bouquets
          search_bar_title: Filtrer les bouquets
          search_results: bouquets disponibles
          add_button: Ajouter un bouquet
          add_title: Nouveau bouquet
          add_subtitle: Description du bouquet
          subject: Sujet du bouquet
          description_title: Objectif du bouquet
          description_info: "Renseignez ici les informations nécessaires à la compréhension du bouquet : politique publique et problématique à laquelle il répond, lien vers toute méthodologie de traitement des données, description de l'organisme porteur du projet, etc."
          owner: Propriétaire du bouquet
        filters:
          - name: Thematiques
            tag: theme
            values:
              - name: Se loger
                tag: ecospheres-se-loger
              - name: Produire
                tag: ecospheres-produire
              - name: Se nourrir
                tag: ecospheres-se-nourrir
              - name: Consommer
                tag: ecospheres-consommer
              - name: Préserver
                tag: ecospheres-preserver
              - name: Se déplacer
                tag: ecospheres-se-deplacer
              - name: Chantiers transverses
                tag: ecospheres-chantiers-transverses
          - name: Sous-Thématiques
            tag: subtheme
            condition_on: theme
            values:
              - name: Construction et rénovation des logements
                tag: ecospheres-construction-et-renovation-des-logements
                condition_on: ecospheres-se-loger
              - name: Aménagements des villes
                tag: ecospheres-amenagements-des-villes
                condition_on: ecospheres-se-loger
              - name: Nucléaire
                tag: ecospheres-nucleaire
                condition_on: ecospheres-produire
              - name: Nucléaire
                tag: ecospheres-nucleaire
                condition_on: ecospheres-produire
              - name: Tertiaire (incluant les bâtiments publics de l'État et des collectivités, hors logement)
                tag: ecospheres-tertiaire-incluant-les-batiments-publics-de-l-etat-et-des-collectivités-hors-logement
                condition_on: ecospheres-produire
              - name: Production d'électricité décarbonée (hors nucléaire)
                tag: ecospheres-production-d-electricite-decarbonee-hors-nucleaire
                condition_on: ecospheres-produire
              - name: Alimentation
                tag: ecospheres-alimentation
                condition_on: ecospheres-se-nourrir
              - name: Agriculture et pêche
                tag: ecospheres-agriculture-et-peche
                condition_on: ecospheres-se-nourrir
              - name: Consommation plus durable (ménages)
                tag: ecospheres-consommation-plus-durable-menages
                condition_on: ecospheres-consommer
              - name: Numérique responsable
                tag: ecospheres-numerique-responsable
                condition_on: ecospheres-consommer
              - name: Achats durables (de l'État, des collectivités et des entreprises)
                tag: ecospheres-achats-durables-de-l-etat-des-collectivites-et-des-entreprises
                condition_on: ecospheres-consommer
              - name: Eau
                tag: ecospheres-eau
                condition_on: ecospheres-preserver
              - name: Sols
                tag: ecospheres-sols
                condition_on: ecospheres-preserver
              - name: Océans et mers
                tag: ecospheres-oceans-et-mers
                condition_on: ecospheres-preserver
              - name: Forêt
                tag: ecospheres-foret
                condition_on: ecospheres-preserver
              - name: Voitures et infrastructures routières
                tag: ecospheres-voitures-et-infrastructures-routieres
                condition_on: ecospheres-se-deplacer
              - name: Mobilité courte distance (hors voiture)
                tag: ecospheres-mobilite-courte-distance-hors-voiture
                condition_on: ecospheres-se-deplacer
              - name: Mobilité longue distance (avion, train)
                tag: ecospheres-mobilite-longue-distance-avion-train
                condition_on: ecospheres-se-deplacer
              - name: Le financement qui permet de définir des trajectoires d'investissement crédibles et cohérentes
                tag: ecospheres-le-financement-qui-permet-de-definir-des-trajectoires-d-investissement-credibles-et-coherentes
                condition_on: ecospheres-chantiers-transverses
              - name: La planification et la différenciation territoriale selon les caractéristiques et les spécificités de chaque territoire, incluant les territoires ultra-marins
                tag: ecospheres-la-planification-et-la-differenciation-territoriale-selon-les-caracteristiques-et-les-specificites-de-chaque-territoire-incluant-les-territoires-ultra-marins
                condition_on: ecospheres-chantiers-transverses
              - name: La transition des filières avec la gestion des emplois, des formations et des compétences
                tag: ecospheres-la-transition-des-filieres-avec-la-gestion-des-emplois-des-formations-et-des-competences
                condition_on: ecospheres-chantiers-transverses
              - name: Les données environnementales
                tag: ecospheres-les-donnees-environnementales
                condition_on: ecospheres-chantiers-transverses
              - name: Les services publics exemplaires
                tag: ecospheres-les-services-publics-exemplaires
                condition_on: ecospheres-chantiers-transverses
              - name: La transition juste et les mesures d’accompagnement, pour ne laisser personne au bord du chemin
                tag: ecospheres-la-transition-juste-et-les-mesures-d-accompagnement-pour-ne-laisser-personne-au-bord-du-chemin
                condition_on: ecospheres-chantiers-transverses
              - name: La sobriété des usages et des ressources
                tag: ecospheres-la-sobriete-des-usages-et-des-ressources
                condition_on: ecospheres-chantiers-transverses
      - name: indicators
        slug: indicators
        type: datasets
        config_type:
          organization: 673dafb02cf54cfb2ccbd118
          topic:
          card: indicators
        extras_key: ecospheres
        list_all: true
        display_metadata: true
        activate_read_more: true
        dataset_editorialization: true
        can_add:
          everyone: true
          authorized_users:
        labels:
          search_page_title: indicateurs
          search_bar_title: Filtrer les indicateurs
          search_results: indicateurs disponibles
        filters:
          - name: Thématique
            tag: theme
            values:
              - name: Mieux se déplacer
                tag: ecospheres-indicateurs-theme--mieux-se-deplacer
              - name: Mieux produire
                tag: ecospheres-indicateurs-theme-mieux-produire
              - name: Autre
                tag: ecospheres-indicateurs-theme-autre
          - name: Enjeu
            tag: enjeu
            values:
              - name: Santé
                tag: ecospheres-indicateurs-enjeu-sante
              - name: Atténuation
                tag: ecospheres-indicateurs-enjeu-attenuation
              - name: Biodiversité
                tag: ecospheres-indicateurs-enjeu-biodiversite
organizations: https://raw.githubusercontent.com/ecolabdata/ecospheres-universe/refs/heads/main/dist/organizations-demo.json
