# config file for ecospheres-front

datagouvfr:
  # data.gouv.fr base URL (use www subdomain on prod)
  base_url: https://demo.data.gouv.fr
  # oauth settings
  oauth_client_id: 66e30254d3cc5d5b52a4b6ec

universe:
  # "universe" topic id
  topic_id: 65141cd780d73f98142e9265
  # universe name, used as bouquets tag
  name: ecospheres

robots:
  disallow:
  sitemap:
  meta: 'noindex, nofollow'

# UI customizations
website:
  title: 'ecologie.data.gouv.fr'
  rf_title: 'RÉPUBLIQUE<br>FRANÇAISE'
  service_logo: '/logos/ecospheres-logo.svg'
  badge:
    display: true
    text: 'BETA'
    style: 'blue-cumulus'
  # leave empty if not pertinent
  logo_operator:
    src: '/logos/ecospheres-logo.svg'
    show_in_header: false
    footer:
      width: '40px'
      height: '219px'
  homepage:
    title:
    subtitle:
    sections:
      - title:
        content:
        sub_section_datasets:
        sub_section_cards:
        sub_section_tiles:
        sub_section_buttons:
    meta_description: ecologie.data.gouv.fr référence et centralise les données de la transition écologique.
  header_button:
    display: true
    label: 'Donnez votre avis'
    link: https://tally.so/r/wLWrzp
  header_search:
    display: true
    placeholder: Rechercher...
    dropdown:
      - text: Rechercher {} dans les <strong>jeux de données</strong>
        route: datasets
      - text: Rechercher {} dans les <strong>bouquets</strong>
        route: bouquets
  search_bar:
    display: true
    placeholder: Rechercher une donnée environnementale
  secondary_search:
    display: false
    name:
    link:
  footer_phrase: 'Ce site est une déclinaison thématique de data.gouv.fr sur les données relatives à la transition écologique et énergétique, réalisé par le Ministère de la Transition écologique, de l’Énergie, du Climat et de la Prévention des risques.'
  footer_external_links:
    - label: 'data.gouv.fr'
      href: 'https://www.data.gouv.fr'
      title: 'data.gouv.fr - nouvelle fenêtre'
    - label: 'legifrance.gouv.fr'
      href: 'https://www.legifrance.gouv.fr/'
      title: 'legifrance - nouvelle fenêtre'
    - label: 'ecologie.gouv.fr'
      href: 'https://ecologie.gouv.fr'
      title: 'ecologie.gouv.fr - nouvelle fenêtre'
    - label: 'gouvernement.fr'
      href: 'https://www.gouvernement.fr'
      title: 'gouvernement.fr - nouvelle fenêtre'
  footer_mandatory_links:
    - label: 'Plan du site'
      to: '/sitemap'
    - label: "Conditions générales d'utilisation"
      to: '/terms'
    - label: 'Politique de confidentialité'
      href: 'https://www.data.gouv.fr/fr/suivi/'
    - label: 'Accessibilité : partiellement conforme'
      to: '/accessibility'
    - label: 'Statistiques'
      href: 'https://dashboard.data.developpement-durable.gouv.fr/superset/dashboard/indicateurs-ecospheres/?standalone=2'
  notice:
    display: true
    content: ⚠️ Vous naviguez sur une version de développement d'ecologie.data.gouv.fr ⚠️
    closeable: false
  menu:
    - text: Accueil
      to: /
    - text: Données
      to: /datasets
    - text: Bouquets
      to: /bouquets
    # TODO: enable when ready
    # - text: Indicateurs
    #   to: /indicators
    - text: Organisations
      to: /organizations
    - text: A propos
      to: /about
  router:
    disable:
      - topics
    pages:
      - title: 'À propos'
        id: 'about'
        route: '/about'
        url: '/ecospheres/pages/about.md'
      - title: 'Accessibilité'
        id: 'accessibility'
        route: '/accessibility'
        url: '/ecospheres/pages/accessibility.md'
      - title: "Conditions générales d'utilisation"
        id: 'terms'
        route: '/terms'
        url: '/ecospheres/pages/terms.md'
  show_quality_component: true
  list_search_topics:
  url_search_topics:
  oauth_option: true
  pagination_sizes:
    organizations_list: 9
    topics_list: 100
    files_list: 6
  contact_email: ecospheres@developpement-durable.gouv.fr
  home_banner_colors:
    - '#D6E3A1'
    - '#BFDCB7'
    - '#A7D4CD'
  matomo:
    host: 'https://stats.data.gouv.fr'
    siteId:
  discussions:
    dataset:
      display: true
      create: true
    topic:
      display: true
      create: true
  datasets:
    organization_filter: true
    add_to_bouquet: true
    # similar to QUALITY_METADATA_BACKEND_IGNORE on data.gouv.fr
    harvest_backends_quality_warning:
      - CSW-ISO-19139
    show_extended_information_panel: true
    banner:
      title: Les jeux de données, qu’est-ce que c’est&nbsp;?
      content: |
        Les jeux de données sont des outils statistiques et analytiques qui permettent d’évaluer et de mesurer divers aspects d’un territoire donné. Ces indicateurs aident à comprendre les dynamiques locales, à identifier des problématiques spécifiques, et à orienter les décisions publiques et les politiques de développement.

        Ils sont essentiels pour un diagnostic territorial et pour le suivi des évolutions dans le temps.
  topics:
    slug: bouquets
    name: bouquet
    extras_key: 'ecospheres'
    themes:
      usage: true
      main_name: thématique
      secondary_name: chantier
    # include a list page with all topics
    list_all: true
    display_metadata: true
    activate_read_more: true
    dataset_editorialization: true
    can_add_topics:
      everyone: true
      authorized_users:
    banner:
      title: Les bouquets, qu’est-ce que c’est&nbsp;?
      content: |
        Les bouquets sont des outils statistiques et analytiques qui permettent d’évaluer et de mesurer divers aspects d’un territoire donné. Ces indicateurs aident à comprendre les dynamiques locales, à identifier des problématiques spécifiques, et à orienter les décisions publiques et les politiques de développement.

        Ils sont essentiels pour un diagnostic territorial et pour le suivi des évolutions dans le temps.
  sitemap:
    - name: Accueil
      path: /
    - name: Bouquets
      path: /bouquets
    - name: Jeux de données
      path: /datasets
    - name: Organisations
      path: /organizations
    - name: À propos
      path: /about
    - name: Conditions générales d’utilisation
      path: /terms
    - name: Accessibilité
      path: /accessibility

themes:
  - name: Se loger
    color: 'var(--blue-ecume-sun-247-moon-675)'
    textColor: 'var(--blue-ecume-975-75)'
    subthemes:
      - name: Construction et rénovation des logements
      - name: Aménagements des villes
  - name: Produire
    color: 'var(--green-archipel-sun-391-moon-716)'
    textColor: 'var(--green-archipel-975-75)'
    subthemes:
      - name: Nucléaire
      - name: Tertiaire (incluant les bâtiments publics de l'État et des collectivités, hors logement)
      - name: Production d'électricité décarbonée (hors nucléaire)
  - name: Se nourrir
    color: 'var(--green-menthe-975-75)'
    textColor: 'var(--green-menthe-sun-373-moon-652)'
    subthemes:
      - name: Alimentation
      - name: Agriculture et pêche
  - name: Consommer
    color: 'var(--green-emeraude-975-75)'
    textColor: 'var(--green-emeraude-sun-425-moon-753)'
    subthemes:
      - name: Consommation plus durable (ménages)
      - name: Numérique responsable
      - name: Achats durables (de l'État, des collectivités et des entreprises)
  - name: Préserver
    color: 'var(--green-bourgeon-975-75)'
    textColor: 'var(--green-bourgeon-sun-425-moon-759)'
    subthemes:
      - name: Eau
      - name: Sols
      - name: Océans et mers
      - name: Forêt
  - name: Se déplacer
    color: 'var(--green-tilleul-verveine-975-75)'
    textColor: 'var(--green-tilleul-verveine-sun-418-moon-817)'
    subthemes:
      - name: Voitures et infrastructures routières
      - name: Mobilité courte distance (hors voiture)
      - name: Mobilité longue distance (avion, train)
  - name: Chantiers transverses
    color: 'var(--blue-ecume-975-75)'
    textColor: 'var(--blue-ecume-sun-247-moon-675)'
    subthemes:
      - name: Le financement qui permet de définir des trajectoires d'investissement crédibles et cohérentes
      - name: La planification et la différenciation territoriale selon les caractéristiques et les spécificités de chaque territoire, incluant les territoires ultra-marins
      - name: La transition des filières avec la gestion des emplois, des formations et des compétences
      - name: Les données environnementales
      - name: Les services publics exemplaires
      - name: La transition juste et les mesures d’accompagnement, pour ne laisser personne au bord du chemin
      - name: La sobriété des usages et des ressources

organizations: https://raw.githubusercontent.com/ecolabdata/ecospheres-universe/refs/heads/main/dist/organizations-demo.json

indicators:
  organization_id: 673dafb02cf54cfb2ccbd118
  global_tag_prefix: ecospheres-indicateurs
  filters:
    - name: Thématique
      id: theme
      color: green-menthe
      values:
        - id: mieux-se-deplacer
          name: Mieux se déplacer
        - id: autre
          name: Autre
        - id: mieux-produire
          name: Mieux produire
    - name: Enjeu
      id: enjeu
      color: blue-ecume
      values:
        - id: sante
          name: Santé
        - id: attenuation
          name: Atténuation
        - id: biodiversite
          name: Biodiversité
