# config file for ecospheres-front

datagouvfr:
  # data.gouv.fr base URL (use www subdomain on prod)
  base_url: https://www.data.gouv.fr
  # oauth settings
  oauth_client_id: 66fa76d405b98d06ca73854a

universe:
  # "universe" topic id
  topic_id: 65e9aa6cb5c809c30c70ee02
  # universe name, used as bouquets tag
  name: univers-ecospheres

robots:
  disallow:
    - /admin
    - /datasets
    - /organizations
  sitemap: https://ecologie.data.gouv.fr/sitemap.xml
  meta: 'index, follow'

# UI customizations
website:
  title: 'ecologie.data.gouv.fr'
  rf_title: 'RÉPUBLIQUE<br>FRANÇAISE'
  service_logo: '/logos/ecospheres-logo.svg'
  badge:
    display: true
    text: 'BETA'
    style: 'blue-cumulus'
  # leave empty if not pertinent
  logo_operator:
  homepage:
    title: 'La plateforme des données de la transition écologique'
    subtitle:
    sections:
      - title:
        content:
        sub_section_datasets:
        sub_section_cards:
        sub_section_tiles:
        sub_section_buttons:
    meta_description: ecologie.data.gouv.fr référence et centralise les données de la transition écologique.
  header_button:
    display: true
    label: 'Donnez votre avis'
    link: https://tally.so/r/wLWrzp
  header_search:
    display: true
    placeholder: Rechercher...
    dropdown:
      - text: Rechercher {} dans les <strong>bouquets</strong>
        route: bouquets
      - text: Rechercher {} dans les <strong>jeux de données</strong>
        route: datasets
  search_bar:
    display: true
    placeholder: Rechercher une donnée environnementale
  secondary_search:
    display: false
    name:
    link:
  footer_phrase: "Ce site est une déclinaison thématique de data.gouv.fr sur les données relatives à l'écologie."
  footer_external_links:
    - label: 'ecologie.gouv.fr'
      href: 'https://ecologie.gouv.fr'
      title: 'ecologie.gouv.fr - nouvelle fenêtre'
    - label: 'data.gouv.fr'
      href: 'https://www.data.gouv.fr'
      title: 'data.gouv.fr - nouvelle fenêtre'
    - label: 'gouvernement.fr'
      href: 'https://www.gouvernement.fr'
      title: 'gouvernement.fr - nouvelle fenêtre'
  footer_mandatory_links:
    - label: 'Plan du site'
      to: '/sitemap'
    - label: "Conditions générales d'utilisation"
      to: '/terms'
    - label: 'Politique de confidentialité'
      href: 'https://www.data.gouv.fr/fr/suivi/'
    - label: 'Accessibilité : non conforme'
      to: '/accessibility'
  notice:
    display: true
    content: Vous naviguez sur une version beta d'ecologie.data.gouv. En savoir plus sur [nos travaux en cours](https://ecospheres.gitbook.io/travaux-en-cours/).
    closeable: false
  menu:
    - text: Accueil
      to: /
    - text: Données
      to: /datasets
    - text: Bouquets
      to: /bouquets
    - text: A propos
      to: /about
  router:
    disable:
      - topics
    pages:
      - title: 'À propos'
        id: 'about'
        route: '/about'
        url: '/ecospheres/pages/about.md'
      - title: 'Accessibilité'
        id: 'accessibility'
        route: '/accessibility'
        url: '/ecospheres/pages/accessibility.md'
      - title: "Conditions générales d'utilisation"
        id: 'terms'
        route: '/terms'
        url: '/ecospheres/pages/terms.md'
  show_quality_component: true
  list_search_topics:
  url_search_topics:
  oauth_option: true
  pagination_sizes:
    organizations_list: 9
    topics_list: 100
    files_list: 6
  contact_email: ecospheres@developpement-durable.gouv.fr
  home_banner_colors:
    - '#D6E3A1'
    - '#BFDCB7'
    - '#A7D4CD'
  matomo:
    host: 'https://stats.data.gouv.fr'
    siteId: 299
  discussions:
    dataset:
      display: true
      create: true
    topic:
      display: true
      create: true
  datasets:
    organization_filter: true
    add_to_bouquet: true
    # similar to QUALITY_METADATA_BACKEND_IGNORE on data.gouv.fr
    harvest_backends_quality_warning:
      - CSW-ISO-19139
    show_extended_information_panel: true
  topics:
    slug: bouquets
    name: bouquet
    extras_key: 'ecospheres'
    themes:
      usage: true
      main_name: thématique
      secondary_name: chantier
    # include a list page with all topics
    list_all: true
    display_metadata: true
    activate_read_more: true
    dataset_editorialization: true
    can_add_topics:
      everyone: true
      authorized_users:
  sitemap:
    - name: Accueil
      path: /
    - name: Bouquets
      path: /bouquets
    - name: Jeux de données
      path: /datasets
    - name: Organisations
      path: /organizations
    - name: À propos
      path: /about
    - name: Conditions générales d’utilisation
      path: /terms
    - name: Accessibilité
      path: /accessibility

themes:
  - name: Se loger
    color: 'var(--blue-ecume-sun-247-moon-675)'
    textColor: 'var(--blue-ecume-975-75)'
    subthemes:
      - name: Construction et rénovation des logements
      - name: Aménagements des villes
  - name: Produire
    color: 'var(--green-archipel-sun-391-moon-716)'
    textColor: 'var(--green-archipel-975-75)'
    subthemes:
      - name: Nucléaire
      - name: Tertiaire (incluant les bâtiments publics de l'État et des collectivités, hors logement)
      - name: Production d'électricité décarbonée (hors nucléaire)
  - name: Se nourrir
    color: 'var(--green-menthe-975-75)'
    textColor: 'var(--green-menthe-sun-373-moon-652)'
    subthemes:
      - name: Alimentation
      - name: Agriculture et pêche
  - name: Consommer
    color: 'var(--green-emeraude-975-75)'
    textColor: 'var(--green-emeraude-sun-425-moon-753)'
    subthemes:
      - name: Consommation plus durable (ménages)
      - name: Numérique responsable
      - name: Achats durables (de l'État, des collectivités et des entreprises)
  - name: Préserver
    color: 'var(--green-bourgeon-975-75)'
    textColor: 'var(--green-bourgeon-sun-425-moon-759)'
    subthemes:
      - name: Eau
      - name: Sols
      - name: Océans et mers
      - name: Forêt
  - name: Se déplacer
    color: 'var(--green-tilleul-verveine-975-75)'
    textColor: 'var(--green-tilleul-verveine-sun-418-moon-817)'
    subthemes:
      - name: Voitures et infrastructures routières
      - name: Mobilité courte distance (hors voiture)
      - name: Mobilité longue distance (avion, train)
  - name: Chantiers transverses
    color: 'var(--blue-ecume-975-75)'
    textColor: 'var(--blue-ecume-sun-247-moon-675)'
    subthemes:
      - name: Le financement qui permet de définir des trajectoires d'investissement crédibles et cohérentes
      - name: La planification et la différenciation territoriale selon les caractéristiques et les spécificités de chaque territoire, incluant les territoires ultra-marins
      - name: La transition des filières avec la gestion des emplois, des formations et des compétences
      - name: Les données environnementales
      - name: Les services publics exemplaires
      - name: La transition juste et les mesures d’accompagnement, pour ne laisser personne au bord du chemin
      - name: La sobriété des usages et des ressources

organizations:
  - ademe
  - agence-de-l-eau-rhone-mediterranee-et-corse
  - agence-de-leau-seine-normandie-1
  - agence-nationale-de-la-cohesion-des-territoires
  - agence-nationale-de-lhabitat
  - agence-nationale-pour-la-renovation-urbaine
  - agence-ore-3
  - airparif-1
  - atmo-auvergne-rhone-alpes
  - atmo-bourgogne-franche-comte
  - atmo-grand-est
  - atmosud
  - bureau-de-recherches-geologiques-et-minieres
  - centre-scientifique-et-technique-du-batiment
  - cerema
  - commission-de-regulation-de-lenergie
  - datagrandest
  - ddt-aisne
  - ddt-ardennes
  - ddt-aveyron
  - ddt-cote-dor
  - ddt-creuse
  - ddt-de-la-loire
  - ddt-de-la-meuse
  - ddt-de-lain
  - ddt-de-lardeche
  - ddt-de-meurthe-et-moselle
  - ddt-deux-sevres
  - ddt-drome
  - ddt-haute-garonne
  - ddt-haute-marne
  - ddt-hautes-alpes
  - ddt-hautes-pyrenees
  - ddt-indre
  - ddt-jura
  - ddt-lot
  - ddt-maine-et-loire
  - ddt-mayenne
  - ddt-nievre
  - ddt-savoie
  - ddt-tarn
  - ddt-tarn-et-garonne
  - ddt-territoire-de-belfort
  - ddt-vaucluse
  - ddt-vienne
  - ddt-yvelines
  - ddtm-alpes-maritimes
  - ddtm-aude
  - ddtm-corse-du-sud
  - ddtm-cotes-darmor
  - ddtm-finistere
  - ddtm-gard
  - ddtm-gironde
  - ddtm-haute-corse
  - ddtm-herault
  - ddtm-morbihan
  - ddtm-pas-de-calais
  - ddtm-pyrenees-orientales
  - ddtm-vendee
  - deal-guadeloupe
  - direction-departementale-des-territoire-du-puy-de-dome
  - direction-departementale-des-territoires-de-charente
  - direction-departementale-des-territoires-de-haute-saone
  - direction-departementale-des-territoires-de-haute-savoie
  - direction-departementale-des-territoires-de-la-correze
  - direction-departementale-des-territoires-de-la-haute-loire
  - direction-departementale-des-territoires-de-la-lozere
  - direction-departementale-des-territoires-de-la-marne
  - direction-departementale-des-territoires-de-la-sarthe
  - direction-departementale-des-territoires-de-lallier
  - direction-departementale-des-territoires-de-lariege
  - direction-departementale-des-territoires-de-laube
  - direction-departementale-des-territoires-de-lessonne
  - direction-departementale-des-territoires-de-lisere
  - direction-departementale-des-territoires-de-loir-et-cher
  - direction-departementale-des-territoires-de-lorne
  - direction-departementale-des-territoires-de-saone-et-loire
  - direction-departementale-des-territoires-de-seine-et-marne
  - direction-departementale-des-territoires-des-alpes-de-haute-provence
  - direction-departementale-des-territoires-des-vosges
  - direction-departementale-des-territoires-deure-et-loir
  - direction-departementale-des-territoires-dindre-et-loire
  - direction-departementale-des-territoires-du-bas-rhin-67
  - direction-departementale-des-territoires-du-cher
  - direction-departementale-des-territoires-du-doubs
  - direction-departementale-des-territoires-du-haut-rhin-68
  - direction-departementale-des-territoires-du-loiret
  - direction-departementale-des-territoires-du-rhone-1
  - direction-departementale-des-territoires-du-val-doise
  - direction-departementale-des-territoires-et-de-la-mer-de-charente-maritime
  - direction-departementale-des-territoires-et-de-la-mer-de-la-somme
  - direction-departementale-des-territoires-et-de-la-mer-de-leure
  - direction-departementale-des-territoires-et-de-la-mer-de-loire-atlantique
  - direction-departementale-des-territoires-et-de-la-mer-des-bouches-du-rhone
  - direction-departementale-des-territoires-et-de-la-mer-des-landes
  - direction-departementale-des-territoires-et-de-la-mer-des-pyrenees-atlantiques
  - direction-departementale-des-territoires-et-de-la-mer-dille-et-vilaine
  - direction-departementale-des-territoires-et-de-la-mer-du-calvados
  - direction-departementale-des-territoires-et-de-la-mer-du-var
  - direction-departementale-et-des-territoires-du-cantal
  - direction-regionale-de-lenvironnement-de-lamenagement-et-du-logement-de-normandie
  - direction-regionale-de-lenvironnement-de-lamenagement-et-du-logement-du-centre-val-de-loire
  - direction-regionale-de-lenvironnement-et-du-logement-bourgogne-franche-comte
  - do-terr-geo-centre
  - dreal-grand-est
  - dreal-provence-alpes-cote-dazur
  - electricite-reseau-distribution-france
  - engie-mobilites-electriques
  - equipe-transport-data-gouv-fr
  - federation-des-parcs-naturels-regionaux-de-france
  - fluo-grand-est
  - geo2france
  - gip-bretagne-environnement
  - grdf
  - ile-de-france-mobilites
  - institut-francais-de-recherche-pour-lexploitation-de-la-mer
  - institut-national-de-l-information-geographique-et-forestiere
  - irstea
  - jvmalin
  - ligair
  - meteo-france
  - ministere-de-l-egalite-des-territoires-et-du-logement
  - ministere-de-la-transition-ecologique
  - morbihan-energies
  - observatoire-de-recherche-montpellierain-de-lenvironnement
  - office-national-des-forets
  - office-public-de-lhabitat-des-landes
  - oise-mobilite-syndicat-mixte-des-transports-collectifs-de-loise
  - open-data-reseaux-energies-1
  - parc-national-de-forets
  - parc-national-des-cevennes
  - parc-national-des-ecrins
  - parc-naturel-regional-de-la-montagne-de-reims
  - parc-naturel-regional-de-la-montagne-de-reims-1
  - parc-naturel-regional-des-vosges-du-nord
  - parc-naturel-regional-du-morvan
  - parc-naturel-regional-du-vercors
  - parcs-nationaux-de-france
  - parcs-naturels-regionaux-de-provence-alpes-cote-dazur
  - regie-autonome-des-transports-parisiens-ratp
  - reseau-de-transport-delectricite
  - section-cadastre-topographie-de-la-polynesie-francaise
  - shom
  - sncf
  - societe-du-grand-paris
  - star
  - syndicat-mixte-des-milieux-aquatiques-et-des-rivieres-de-laude
  - syndicat-mixte-des-mobilites-de-laire-grenobloise
  - syndicat-mixte-eptb-meurthe-madon
  - systeme-d-information-sur-l-eau
  - systeme-dinformation-sur-la-biodiversite
  - twisto
