# config file for ecospheres-front

datagouvfr:
  # data.gouv.fr base URL (use www subdomain on prod)
  base_url: https://demo.data.gouv.fr
  # oauth settings
  oauth_client_id: 66e30254d3cc5d5b52a4b6ec

universe:
  # "universe" topic id
  topic_id: 65141cd780d73f98142e9265
  # universe name, used as bouquets tag
  name: simplifions

robots:
  disallow:
  sitemap:
  meta: 'noindex, nofollow'

# UI customizations
website:
  title: 'toto.data.gouv.fr'
  rf_title: 'RÉPUBLIQUE<br>FRANÇAISE'
  service_logo: '/logos/ecospheres-logo.svg'
  badge:
    display: true
    text: 'BETA'
    style: 'blue-cumulus'
  # leave empty if not pertinent
  logo_operator:
    src: '/logos/ecospheres-logo.svg'
    show_in_header: false
    footer:
      width: '40px'
      height: '219px'
  homepage:
    title: coucou toto
    subtitle: subtitle toto
    sections:
      - title: salut toto
        content: content toto
        sub_section_datasets:
        sub_section_cards:
        sub_section_tiles:
        sub_section_buttons:
    meta_description: ecologie.data.gouv.fr référence et centralise les données de la transition écologique.
  header_button:
    display: true
    label: 'Donnez votre avis'
    link: https://tally.so/r/wLWrzp
  search_config:
    header_search:
      display: true
      placeholder: Rechercher...
      dropdown:
        - text: Rechercher {} dans les <strong>jeux de données</strong>
          route: datasets
        - text: Rechercher {} dans les <strong>bouquets</strong>
          route: bouquets
    pages:
      - name: usecases
        slug: usecases
        type: topics
        config_type:
          organization:
        extras_key: usecases
        list_all: true
        display_metadata: true
        activate_read_more: true
        dataset_editorialization: true
        can_add:
          everyone: true
          authorized_users:
        labels:
          search_page_title: cas d'usages
          search_bar_title: Filtrer les cas d'usages
          search_results: cas disponibles
          add_button: Ajouter un cas d'usage
          add_title: Nouveau cas d'usage
          add_subtitle: Description du cas d'usage
          subject: Sujet du cas d'usage
          description_title: Objectif du cas d'usage
          description_info: "Renseignez ici les informations nécessaires à la compréhension du cas d'usage"
          owner: Propriétaire du cas d'usage
        filters:
          - name: Thematiques
            tag: theme
            values:
              - name: Se loger
                tag: se-loger
              - name: Se Nourrir
                tag: se-nourrir
          - name: Sous-Thématiques
            tag: subtheme
            condition_on: theme
            values:
              - name: Test 1
                tag: test1
                condition_on: se-loger
              - name: Test 2
                tag: test2
                condition_on: se-loger
              - name: Test 3
                tag: test3
                condition_on: se-nourrir
              - name: Test 4
                tag: test4
                condition_on: se-nourrir
          - name: Type de structures
            tag: structure
            values:
              - name: Administrations
                tag: admin
              - name: Citoyens
                tag: citizen
              - name: Entreprises
                tag: company
      - name: hackathons
        slug: hackathons
        type: datasets
        config_type:
          organization: 673dafb02cf54cfb2ccbd118
          topic:
          card: indicators
        extras_key: hackathons
        list_all: true
        display_metadata: true
        activate_read_more: true
        dataset_editorialization: true
        can_add:
          everyone: true
          authorized_users:
        labels:
          search_page_title: indicateurs
          search_bar_title: Filtrer les indicateurs
          search_results: indicateurs disponibles
          add_button: Ajouter un indicateur
          add_title: Nouvel indicateur
          add_subtitle: Description de l'indicateur
          subject: Sujet de l'indicateur
          description_title: Objectif de l'indicateur
          description_info: "Renseignez ici les informations nécessaires à la compréhension de l'indicateur"
          owner: Propriétaire de l'indicateur
        filters:
          - name: Type de structures
            tag: structure
            values:
              - name: Administrations
                tag: 'ecospheres-indicateurs-sous-famille-emissions'
              - name: Citoyens
                tag: citizen
              - name: Entreprises
                tag: company

  header_search:
    display: true
    placeholder: Rechercher...
    dropdown:
      - text: Rechercher {} dans les <strong>jeux de données</strong>
        route: datasets
      - text: Rechercher {} dans les <strong>bouquets</strong>
        route: bouquets
  search_bar:
    display: true
    placeholder: Rechercher une donnée environnementale
  secondary_search:
    display: false
    name:
    link:
  footer_phrase: 'Ce site est une déclinaison thématique de data.gouv.fr sur les données relatives à la transition écologique et énergétique, réalisé par le Ministère de la Transition écologique, de l’Énergie, du Climat et de la Prévention des risques.'
  footer_external_links:
    - label: 'data.gouv.fr'
      href: 'https://www.data.gouv.fr'
      title: 'data.gouv.fr - nouvelle fenêtre'
    - label: 'legifrance.gouv.fr'
      href: 'https://www.legifrance.gouv.fr/'
      title: 'legifrance - nouvelle fenêtre'
    - label: 'ecologie.gouv.fr'
      href: 'https://ecologie.gouv.fr'
      title: 'ecologie.gouv.fr - nouvelle fenêtre'
    - label: 'gouvernement.fr'
      href: 'https://www.gouvernement.fr'
      title: 'gouvernement.fr - nouvelle fenêtre'
  footer_mandatory_links:
    - label: 'Plan du site'
      to: '/sitemap'
    - label: "Conditions générales d'utilisation"
      to: '/terms'
    - label: 'Politique de confidentialité'
      href: 'https://www.data.gouv.fr/fr/suivi/'
    - label: 'Accessibilité : partiellement conforme'
      to: '/accessibility'
  notice:
    display: true
    content: ⚠️ Vous naviguez sur une version de développement d'ecologie.data.gouv.fr ⚠️
    closeable: false
  menu:
    - text: Accueil
      to: /
    - text: Données
      to: /datasets
    - text: Organisations
      to: /organizations
    - text: A propos
      to: /about
    - text: Hack
      to: /hackathons
    - text: UC
      to: /usecases
  router:
    disable:
      - topics
    pages:
      - title: 'À propos'
        id: 'about'
        route: '/about'
        url: '/ecospheres/pages/about.md'
      - title: 'Accessibilité'
        id: 'accessibility'
        route: '/accessibility'
        url: '/ecospheres/pages/accessibility.md'
      - title: "Conditions générales d'utilisation"
        id: 'terms'
        route: '/terms'
        url: '/ecospheres/pages/terms.md'
  show_quality_component: true
  list_search_topics:
  url_search_topics:
  oauth_option: true
  pagination_sizes:
    organizations_list: 9
    topics_list: 100
    files_list: 6
  contact_email: ecospheres@developpement-durable.gouv.fr
  home_banner_colors:
    - '#D6E3A1'
    - '#BFDCB7'
    - '#A7D4CD'
  matomo:
    host: 'https://stats.data.gouv.fr'
    siteId:
  discussions:
    dataset:
      display: true
      create: true
    topic:
      display: true
      create: true
  datasets:
    organization_filter: true
    add_to_bouquet: true
    # similar to QUALITY_METADATA_BACKEND_IGNORE on data.gouv.fr
    harvest_backends_quality_warning:
      - CSW-ISO-19139
    show_extended_information_panel: true
  sitemap:
    - name: Accueil
      path: /
    - name: Bouquets
      path: /bouquets
    - name: Jeux de données
      path: /datasets
    - name: Organisations
      path: /organizations
    - name: À propos
      path: /about
    - name: Conditions générales d’utilisation
      path: /terms
    - name: Accessibilité
      path: /accessibility
organizations: https://raw.githubusercontent.com/ecolabdata/ecospheres-universe/refs/heads/main/dist/organizations-demo.json
