# config file for meteo-france

datagouvfr:
  # data.gouv.fr base URL
  base_url: https://demo.data.gouv.fr
  # oauth settings
  oauth_client_id:
  # pkce client secret, explicitely public
  oauth_client_secret:

universe:
  # "universe" topic id
  topic_id: 650da7e9ac89b5a2ac75a11a # meteo-test
  # universe name, used as bouquets tag
  name: meteo-france

# UI customizations
website:
  title: 'meteo.data.gouv.fr'
  rf_title: 'RÉPUBLIQUE<br>
    FRANÇAISE'
  service_logo: '/logos/meteo-france-logo.svg'
  badge:
    display: true
    text: 'BETA'
    style: 'blue-cumulus'
  # leave empty if not pertinent
  logo_operator: 'https://static.data.gouv.fr/avatars/81/6374003e904fad9ddac7436315fd15-100.png'
  homepage_title: 'La météo et le climat en Open Data'
  homepage_subtitle: 'meteo.data.gouv.fr centralise et structure les données publiques relatives à la météo et au climat. Vous y trouverez des données téléchargeables et utilisables de manière libre et gratuite.'
  header_button:
    display: true
    label: 'Donnez votre avis'
    link: https://tally.so/r/wQ7y47
  search_bar:
    display: true
    placeholder: 'Rechercher un jeu de données'
  secondary_search:
    display: true
    name: 'Recherche guidée'
    link: '/form'
  menu_items:
    - name: 'Accueil'
      id: 'home'
      linkPage: '/'
      type: 'component'
      display_menu: false
    - name: 'Données'
      id: 'datasets'
      linkPage: '/datasets'
      type: 'component'
      display_menu: true
    - name: 'Recherche guidée'
      id: 'FormMF'
      linkPage: '/form'
      type: 'custom'
      path: '../custom/meteo/views/FormMF.vue'
      display_menu: true
    - name: 'A propos'
      id: 'about'
      linkPage: '/about'
      type: 'page'
      url: 'https://gist.githubusercontent.com/geoffreyaldebert/4e95103bff159c578db3941619fb9cfd/raw/7afdf99a23f45041e7e9eb391b65afeb6025e1cd/gistfile1.txt'
      display_menu: true
  # img should be square
  home_buttons:
  show_topic_charts: true
  show_quality_component: true
  show_dataset_metadata_panel: false
  show_dataset_discussions: false
  list_highlighted_topics:
    - id: '653a6eee7a6aa39deaec2de9'
      name: 'Données climatologiques de base'
    - id: '653a6f43e96894d0275c994c'
      name: 'Données climatologiques de référence pour le changement climatique'
  oauth_option: false
  # display settings
  pagination_sizes:
    organizations_list: 9
    topics_list: 100
    files_list: 6
  home_banner_colors:
    - '#F7EED4'
    - '#ECEEE6'
    - '#E2EEF8'
  env: 'dev'

# list of organisations' ids that should be handled by the portal
# to find an id go to https://www.data.gouv.fr/fr/organizations/ministere-de-la-transition-ecologique/
# then Informations > ID at the bottom of the page
organizations:
