# config file for meteo-france

datagouvfr:
  # data.gouv.fr base URL
  base_url: https://www.data.gouv.fr
  # oauth settings
  oauth_client_id: 66d1ecc08223699099a7c24b
  # pkce client secret, explicitely public
  oauth_client_secret: BWJW8QxyT0h1dauey71e1JjgxtIJZDYtV07mS3oSfnIjSvKu4K

universe:
  # "universe" topic id
  topic_id: 6571f222129681e83de11aa2 # meteo-test
  # universe name, used as bouquets tag
  name: meteo-france

robots:
  disallow:
    - /
  sitemap:

# UI customizations
website:
  title: 'meteo.data.gouv.fr'
  rf_title: 'RÉPUBLIQUE<br>
    FRANÇAISE'
  service_logo: '/logos/meteo-france-logo.svg'
  badge:
    display: false
    text: 'BETA'
    style: 'blue-cumulus'
  # leave empty if not pertinent
  homepage:
    title: 'La météo et le climat en Open Data'
    subtitle: 'meteo.data.gouv.fr vise à référencer, héberger et diffuser les données publiques météorologiques produites par Météo-France. Vous y trouverez des données téléchargeables et utilisables de manière libre et gratuite.'
    sections:
      - title: Bouquets de données
        content:
        sub_section_datasets:
        sub_section_cards:
          title:
          cards:
            - name: 'Données climatologiques (par station et spatialisées)'
              description: 'Données climatologiques pour toutes les stations françaises depuis leur ouverture, pour tous les paramètres disponibles.'
              url: 'bouquets?theme=Données+climatologiques'
              image_url: '/meteo-france/assets/climatologie.png'
            - name: 'Données de référence pour le changement climatique'
              description: 'Données recommandées par Météo-France pour réaliser des diagnostics et études climatiques.'
              url: 'bouquets?theme=Données+de+référence+pour+le+changement+climatique'
              image_url: '/meteo-france/assets/changement.png'
            - name: 'Données de Prévision Numérique du Temps (PNT)'
              description: 'Données temps réel des dernières prévisions des modèles de prévision numérique jusqu’à 4 jours d’échéance.'
              url: 'bouquets?theme=Données+de+prévision+numérique+du+temps+(PNT)'
              image_url: '/meteo-france/assets/pnt.png'
        sub_section_tiles:
        sub_section_buttons:
      - title: Actualités
        content: >-
          Retours sur le hackathon du 8 et 9 avril dernier 🚀


          [En savoir plus](/hackathon)
        sub_section_datasets:
        sub_section_cards:
        sub_section_tiles:
        sub_section_buttons:
    meta_description:
  header_button:
    display: true
    label: 'Donnez votre avis'
    link: https://tally.so/r/wQ7y47
  header_search:
    display: true
    placeholder: Rechercher...
  search_bar:
    display: true
    placeholder: 'Rechercher un jeu de données'
  secondary_search:
    display: true
    name: 'Recherche guidée'
    link: '/form'
  menu:
    - text: Accès aux données
      to: /bouquets
    - text: Recherche guidée
      to: /form
    - text: 'Hackathon le 8 et 9 avril 🚀'
      to: /hackathon
    - text: A propos
      to: /about
  router:
    disable:
      - organizations_routes
      - topics
    pages:
      - title: 'A propos'
        id: 'about'
        route: '/about'
        url: '/meteo-france/pages/about.md'
      - title: 'Accessibilité'
        id: 'accessibility'
        route: '/accessibility'
        url: '/meteo-france/pages/accessibility.md'
      - title: 'Hackathon le 8 et 9 avril 🚀'
        id: 'hackathon'
        route: '/hackathon'
        url: '/meteo-france/pages/hackathon.md'
  show_quality_component: true
  list_search_topics:
  url_search_topics: 'datasets'
  oauth_option: true
  footer_phrase: 'Ce site est une déclinaison thématique de data.gouv.fr sur les données relatives à la météo et au climat réalisé en collaboration avec Météo-France.'
  footer_external_links:
    - label: 'meteofrance.com'
      href: 'https://meteofrance.com/'
    - label: 'Portail des API Météo-France'
      href: 'https://portail-api.meteofrance.fr/'
    - label: 'data.gouv.fr'
      href: 'https://www.data.gouv.fr'
  footer_mandatory_links:
    - label: 'Licences'
      href: 'https://www.data.gouv.fr/fr/pages/legal/licences/'
    - label: "Conditions générales d'utilisation"
      href: 'https://www.data.gouv.fr/fr/terms/'
    - label: 'Politique de confidentialité'
      href: 'https://www.data.gouv.fr/fr/suivi/'
    - label: 'Accessibilité : non conforme'
      to: '/accessibility'
  logo_operator: 'https://static.data.gouv.fr/avatars/81/6374003e904fad9ddac7436315fd15-100.png'
  notice:
    display: false
    content: Notice avec un [lien beta](/beta) et du _style_
    closeable: false
  # display settings
  pagination_sizes:
    organizations_list: 9
    topics_list: 100
    files_list: 6
  home_banner_colors:
    - '#F7EED4'
    - '#ECEEE6'
    - '#E2EEF8'
  env: 'prod'
  matomo:
    host: 'https://stats.data.gouv.fr'
    siteId: 292
  discussions:
    dataset:
      display: true
      create: true
    topic:
      display: false
      create: false
  datasets:
    organization_filter: false
    add_to_bouquet: true
    # similar to QUALITY_METADATA_BACKEND_IGNORE on data.gouv.fr
    harvest_backends_quality_warning: []
    show_extended_information_panel: false
  topics:
    slug: bouquets
    name: bouquet de donnée
    extras_key: 'meteofrance'
    themes:
      usage: true
      main_name: catégorie
      secondary_name: sous-catégorie
    # include a list page with all topics
    list_all: false
    display_metadata: false
    activate_read_more: false
    dataset_editorialization: false
    can_add_topics:
      everyone: false
      authorized_users:
        - 6230733357772160a4f77fbaxx
themes:
  - name: Informations sur les stations
    color: 043574
    textColor: FFFFFF
    subthemes:
      - name: Stations du réseau Météo-France
      - name: Stations complémentaires
  - name: Données climatologiques
    color: 1E929E
    textColor: FFFFFF
    subthemes:
      - name: Données à la station du réseau Météo-France
      - name: Données stations complémentaires
      - name: Données spatialisées
  - name: Données de référence pour le changement climatique
    color: 1E929E
    textColor: FFFFFF
    subthemes:
      - name: Données à la station
      - name: Données spatialisées
  - name: Données de prévision numérique du temps (PNT)
    color: 1E929E
    textColor: FFFFFF
    subthemes:
      - name: Paquets issus du modèle AROME
      - name: Paquets issus du modèle ARPEGE
      - name: Paquets issus de modèle de vagues
      - name: Paquets issus de modèle de surcote océanique
  # - name: Données d'observations
  #   color: 1E929E
  #   textColor: FFFFFF
  #   subthemes:
  #     - name: Données d'observations
  # - name: Références climatiques
  #   color: 1E929E
  #   textColor: FFFFFF
  #   subthemes:
  #     - name: Référence à la station
  #     - name: Référence spatialisées

# list of organisations' ids that should be handled by the portal
# to find an id go to https://www.data.gouv.fr/fr/organizations/ministere-de-la-transition-ecologique/
# then Informations > ID at the bottom of the page
organizations:
