name: Generate robots.txt

on:
  push:
    branches:
      # deployment branches
      - ecospheres-prod
      - ecospheres-demo
      # - meteodatagouvfr-prod
      # - defisdatagouvfr-prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: 'npm'
      - run: npm ci
      - run: npm run generate-robots-txt
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add public/robots.txt
          git commit -m "Update robots.txt [skip ci]" || echo "No changes to commit"
          git push origin ${{ github.ref }}
